export const SYMBOL_TO_SLUG: Record<string, string> = {
  RELIANCE: 'reliance-industries',
  TCS: 'tata-consultancy-services',
  HDFCBANK: 'hdfc-bank',
  INFY: 'infosys',
  ICICIBANK: 'icici-bank',
  HINDUNILVR: 'hindustan-unilever',
  ITC: 'itc',
  SBIN: 'state-bank-of-india',
  BAJFINANCE: 'bajaj-finance',
  BHARTIARTL: 'bharti-airtel',
  KOTAKBANK: 'kotak-mahindra-bank',
  LT: 'larsen-toubro',
  WIPRO: 'wipro',
  AXISBANK: 'axis-bank',
  MARUTI: 'maruti-suzuki',
  SUNPHARMA: 'sun-pharmaceutical-industries',
  TITAN: 'titan-company',
  ASIANPAINT: 'asian-paints',
  NTPC: 'ntpc',
  ONGC: 'oil-natural-gas-corporation',
  POWERGRID: 'power-grid-corporation-of-india',
  ULTRACEMCO: 'ultratech-cement',
  HCLTECH: 'hcl-technologies',
  ADANIPORTS: 'adani-ports-sez',
  GRASIM: 'grasim-industries',
  JSWSTEEL: 'jsw-steel',
  TECHM: 'tech-mahindra',
  BRITANNIA: 'britannia-industries',
  DRREDDY: 'dr-reddys-laboratories',
  CIPLA: 'cipla',
  NESTLEIND: 'nestle-india',
  HEROMOTOCO: 'hero-motocorp',
  BAJAJFINSV: 'bajaj-finserv',
  TATAMOTORS: 'tata-motors',
  TATASTEEL: 'tata-steel',
  'M&M': 'mahindra-mahindra',
  PNB: 'punjab-national-bank',
  HDFCLIFE: 'hdfc-life-insurance-company',
  SBILIFE: 'sbi-life-insurance-company',
  EICHERMOT: 'eicher-motors',
  COALINDIA: 'coal-india',
  BPCL: 'bharat-petroleum-corporation',
  HINDALCO: 'hindalco-industries',
  DABUR: 'dabur-india',
  MARICO: 'marico',
  TORNTPHARMA: 'torrent-pharmaceuticals',
  DIVISLAB: 'divis-laboratories',
  APOLLOHOSP: 'apollo-hospitals-enterprise',
  INDUSINDBK: 'indusind-bank',
  'BAJAJ-AUTO': 'bajaj-auto',
  OFSS: 'oracle-financial-services-software',
  CASTROLIND: 'castrol-india',
  ABSLAMC: 'aditya-birla-sun-life-amc',
  LICI: 'life-insurance-corporation-of-india',
  NMDC: 'nmdc',
}

export function toSlug(symbol: string): string {
  return SYMBOL_TO_SLUG[symbol] ?? symbol.toLowerCase().replace(/_/g, '-')
}
